server:
  port: 8080
spring:
  web:
    resources:
      static-locations: classpath:/
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/store?serverTimezone=UTC&character=utf-8
      username: root
      password: 1234
  main:
    allow-bean-definition-overriding: true
  
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: t_
      id-type: ASSIGN_ID

